### ISSUE TITLE
Error detected, TextChangedI Autocommands for "<buffer=5>"

### ISSUE THREAD

**Issue by Staz0r** [NvChad/ui#348] opened 2024-10-04 06:50 UTC
**Describe the bug**
Writing a c++ file, everytime I keyed in some symbols like  `(`,  `,` or `>` this error is shown

**To Reproduce**
1. Open nvim
2. Make a .cpp file
3. Type in the symbols above

**Expected behavior**
Nothing serious should be happening

**Screenshots**
TextChangedI Autocommands for "<buffer=5>"                                   method textDocument/signatureHelp is not supported by any of the servers registered for the current buffer

**Desktop (please complete the following information):**
 - Operating System Windows 11
 - Version of Neovim 0.10.1

**Comment by siduck** [comment] 2024-10-04 13:27
show a video

**Comment by Staz0r** [comment] 2024-10-06 03:21
https://github.com/user-attachments/assets/8441f81a-f383-4a67-a8b3-79e26ef04542

Every key that appeared after the error, was the key that I pressed. The last part about :q was just saying that there was a previous buffer that has not been saved, its irrelevant.

**Comment by siduck** [comment] 2024-10-06 03:41
i dont code in C++, it works fine here


https://github.com/user-attachments/assets/a5c24c1d-ea52-4fc7-9fe7-72bab9ba27b9

**Comment by jamesredwards** [comment] 2024-10-07 12:37
Experiencing the same issue in C projects. Using Linux. Nvim version 0.10.1. NvChad 2.5

**Comment by siduck** [comment] 2024-10-07 12:51
where did you download clangd lsp from :/ 

it supports signature

**Comment by siduck** [comment] 2024-10-07 12:52
![image](https://github.com/user-attachments/assets/f30863d2-6c93-41ad-aec6-bc9bae55b467)

**Comment by jamesredwards** [comment] 2024-10-07 13:40
> where did you download clangd lsp from :/
> 
> it supports signature

Mason

**Comment by siduck** [comment] 2024-10-07 13:55
why i am unable to reproduce the issue, do you   have some common c project that i can try on

**Comment by Staz0r** [comment] 2024-10-07 14:05
I'm not really familiar with lua, so all I did was just copy pasting installation code.
I remember everything working just fine before though. Do you need to see all my plugins list for reference?

**Comment by jamesredwards** [comment] 2024-10-07 14:05
I just tried it again with a basic hello world program. Same issue. I'll try a completely fresh install of nvchad on a different machine tonight with only clangd in lspconfig.

**Comment by siduck** [comment] 2024-10-13 01:19
should be fixed.

**Closed as completed by siduck** 2024-10-13 01:19 UTC

**Comment by Staz0r** [comment] 2024-10-14 05:04
Its working now, thank you!
