### ISSUE TITLE
NVim exits without any message when I scroll the list of themes

### ISSUE THREAD

**Issue by A-tA-v** [NvChad/ui#276] opened 2024-04-24 14:41 UTC
**Describe the bug**
NVim exits without any message when I scroll the list of themes using arrow keys.
Possibly, this happens with certain themes.

**Desktop (please complete the following information):**
 - Operating System: OSX Sonoma, Apple Silicon M1
 - Terminal: iTerm2
 - Version of Neovim: 0.9.5

**Comment by siduck** [comment] 2024-04-24 14:59
show video plz

**Comment by A-tA-v** [comment] 2024-04-24 18:13
Sorry, I am not allowed to share a screen record. But I did some investigation. It turns out, the crash happens in iTerm2, and happens randomly. One time I can scroll through the theme normally, then nvim stumbles on that same theme the next time. However, OSX native terminal works normally. I can share a log-file, if you directed me to a relevant folder/file

**Comment by siduck** [comment] 2024-04-25 00:07
hmm if i cant  reproduce  this then idk how to fix it

**Comment by A-tA-v** [comment] 2024-04-25 11:07
I understand. But even if I provide video there is literally nothing - navigating the list of themes and suddenly nvim exits without any message. That it. Btw, I changed font in my iTerm2 settings to DroidSansM Nerd Font Mono, size 16, and Color Presets to "Tango Light". Maybe this can help. 
I attached debugger to the nvim process. Actually, there are two processes: "nvim" and "nvim-embed". I tried both with the same result. Unfortunately, debugger shows nothing useful:
```
lldb --attach-pid 46061
(lldb) process attach --pid 46061
Process 46061 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00000001925c4340 libsystem_kernel.dylib`kevent + 8
libsystem_kernel.dylib`kevent:
->  0x1925c4340 <+8>:  b.lo   0x1925c4360               ; <+40>
    0x1925c4344 <+12>: pacibsp
    0x1925c4348 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1925c434c <+20>: mov    x29, sp
Target 0: (nvim) stopped.
Executable module set to "/opt/homebrew/Cellar/neovim/0.9.5/bin/nvim".
Architecture set to: arm64-apple-macosx-.
(lldb) c
Process 46061 resuming
Process 46061 exited with status = 1 (0x00000001)      # <---- HERE the unexpected exit happened. 
```

**Comment by siduck** [comment] 2024-04-25 11:23
probably font issue then, you could try other terminal like alacritty/wezterm/kitty.

The amount of nvim issues i see with default mac terminal/ iterm2 scares me :fearful:

**Comment by siduck** [comment] 2024-04-28 11:04
do you have ripgrep and fd installed?

**Comment by siduck** [comment] 2024-06-09 15:22
Closing, as unable to reproduce

**Closed as completed** 2024-06-09 15:21 UTC
